### ISSUE TITLE
NullPointerException in WebpFrameLoader#onFrameReady

### ISSUE THREAD

**Issue by superxlcr** [zjupure/GlideWebpDecoder#102]
crash stacktrace:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.bumptech.glide.integration.webp.decoder.WebpFrameLoader$a.onFrameReady()' on a null object reference
	at com.bumptech.glide.integration.webp.decoder.WebpFrameLoader.onFrameReady(WebpFrameLoader.java)
	at com.bumptech.glide.integration.webp.decoder.WebpFrameLoader$b.handleMessage(WebpFrameLoader.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	...

library version: 2.0.4.11.0
	
related code:
            // The callbacks may unregister when onFrameReady is called, so iterate in reverse to avoid
            // concurrent modifications.
            for (int i = callbacks.size() - 1; i >= 0; i--) {
                FrameCallback cb = callbacks.get(i);
                cb.onFrameReady();
            }

it seems like the FrameCallback got from callbacks list is null

**Comment by zjupure** [comment]
You subscribe a null callback to WebpFrameLoader?
