### ISSUE TITLE
希望公开OnEveryFrameListener接口及其set方法

### ISSUE THREAD

**Issue by ZouYongpeng** [zjupure/GlideWebpDecoder#106]
如题，我需要监听webp资源的每帧回调以实现功能，发现OnEveryFrameListener接口及其set方法是protected的，调用不了，希望能开放使用。
![image](https://user-images.githubusercontent.com/37317487/218413747-c4875520-78ec-4768-86e5-24adf8c5c88b.png)
![image](https://user-images.githubusercontent.com/37317487/218413791-619b1570-a289-44ac-8c02-cc09298dd106.png)

**Comment by zjupure** [comment]
WebpFrameLoader not public API and user should not it.
