### ISSUE TITLE
加载webp动图，结果图片缩小了

### ISSUE THREAD

**Issue by wuxiangpeng** [zjupure/GlideWebpDecoder#107]
Transformation<Bitmap> circleCrop = new CircleCrop();
        GlideApp.with(context)
                .load(url)
                .optionalTransform(circleCrop)
                .optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(circleCrop))
                .into(iv);

**Comment by zjupure** [comment]
默认会根据ImageView的大小进行降采样缩放图片，如果不需要可以使用Glide的API override width/height
