### ISSUE TITLE
首帧预览 功能

### ISSUE THREAD

**Issue by meijingkang** [zjupure/GlideWebpDecoder#109]
### 能否支持首帧预览功能，如果webp图片比较大的话，就需要加载很长时间才能显示。

看了下源码，不知道分析的对不对。 我看好像是从流中将所有的字节读到后，才开始解析webp，是因为lipwebp库只支持这种解析方式么， 能否支持先读取首帧，然后就给界面展示，后续当所有数据加载完成后开始展示动画呢

**Comment by zjupure** [comment]
可以尝试先以asBitmap形式加载，然后再切换成asDrawable，使用Glide的自定义Target

**Comment by meijingkang** [comment]
我晚点试试
