### ISSUE TITLE
有没有非androidX的版本引用

### ISSUE THREAD

**Issue by a1506766443** [zjupure/GlideWebpDecoder#113]

**Comment by zjupure** [comment]
Notice

Since Glide 4.10.0 has migrate to AndroidX, so your project must use AndroidX with Glide 4.10.0+.

WebpDecoder with AndroidX support starts from version 1.6.{GLIDE_VERSION} and won't support glide version below 4.10.0 anymore.

不再支持非AndroidX版本，建议尽早升级AndroidX，1.6之前版本是非AndroidX的
