### ISSUE TITLE
Live wallpaper sample?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#12]
Can you please show how to use the decoder to view GIF/WEBP animation in live wallpaper, including how to scale there using popular scaling types (fit-center, center-crop,center-inside) ?

Something similar to what they did here:
https://github.com/koral--/android-gif-drawable

But this time with webp support too.

**Comment by zjupure** [comment]
see [Glide doc](https://bumptech.github.io/glide/) for basic usage. If you do not need transformation, you have nothing else to do besides adding dependencies.

If you need transformation, you should use `WebpDrawableTransformation` when build a Glide request. The following is some code snippet, your can also find it in sample project.

```Java
Transformation<Bitmap> circleCrop = new CircleCrop();
GlideApp.with(mContext)
                .load(url)
                .optionalTransform(circleCrop)
                .optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(circleCrop))
                .into(imageView);
```

**Comment by zjupure** [comment]
@AndroidDeveloperLB [Glide Targets](https://bumptech.github.io/glide/doc/targets.html#custom-targets), see glide custom targets. This library is associated with Glide, you should read glide docs first. I have no plan to support live wallpaper or write sample.

**Comment by AndroidDeveloperLB** [comment]
I see. Can you please show how to use this library to view a WEBP animation on an ImageView, here:

https://github.com/zjupure/GlideWebpDecoder/issues/13

?
