### ISSUE TITLE
Request: please explain how to use the library

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#13]
The repository webpage only shows the dependencies. But what about how to use it?

**Comment by zjupure** [comment]
Please see Glide [docs](https://github.com/bumptech/glide) and run sample project to see how animated webp is loaded.

**Comment by AndroidDeveloperLB** [comment]
The reason I wrote this, is not because of the sample or the docs of Glide.
It's because this repository only mentions how to use its dependency, but not how to actually use it. Not even the simplest way to do it.

**Comment by zjupure** [comment]
There is no difference between jpg/png or gif/webp with Glide when you load without transformation. The exist code can still work well when the image url change to a webp image. So you only need to add dependencies in your build.gradle. Only with BitmapTransformtaion, you need add some extra code to support it. If you are not familiar with Glide, please read docs and write demo with Glide first.

**Comment by AndroidDeveloperLB** [comment]
I am familiar with Glide, but not with this library.
You say that once I just use the dependency, and I try to load WebP animation, it will work as if I'm loading a PNG file, even though I've not used a single piece of code from this library?

**Comment by zjupure** [comment]
Yes, Glide annotation processor will do everything for you automatically. You can read the Glide source code and related integration to find the answer. The Library only insert a WebpDecoder into Glide built-in decoder lists to support webp image.

**Comment by AndroidDeveloperLB** [comment]
Wow this sounds so cool!
You've created some sort of plugin that gets attached automatically to a different library, and that library uses it without me telling it to do it.

I really want to try it out, but for now I still have this issue of importing the sample: https://github.com/zjupure/GlideWebpDecoder/issues/11

That's why I wanted to try an alternative, of the most simple way to show a WebP animation (directly from file, for example).
