### ISSUE TITLE
how to get webp bitmap?

### ISSUE THREAD

**Issue by magic0908** [zjupure/GlideWebpDecoder#21]
this is code:
File file = Glide.with(activity).asFile().load(url).submit().get();
Bitmap bitmap = WebpBitmapFactory.decodeFile(file.getAbsolutePath());

or

Bitmap bitmap = Glide.with(context).asBitmap().load(url).submit().get();

I tried two methods get bitmap,but always is null;

this is webp url:
http://osscdn.ixingtu.com/musi_file/20181108/a20540641eb7de9a8bf186261a8ccf57.webp

please help me!

**Comment by zjupure** [comment]
Animated webp can only be decoded to drawable with multiple frame bitmap. You just want to get the first frame bitmap?

**Comment by magic0908** [comment]
yes , I can get the fist frame bitmap
thank you for your help! I've solved it.
