### ISSUE TITLE
Possible bug: animation can't resume after some time

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#22]
I wanted to use this library as a way to pass a Bitmap that was drawn to, frame by frame.

For this, I had to have a workaround that draws the Drawable (GifDrawable or WebpDrawable) into a Bitmap , and then decide what to do with it.

It works very well, but if I let the device sleep for a while (about 20 seconds or so), and return to it, it fails to resume the animation. If I turn off the screen and turn it on again after a short time, it works fine, though.

Any idea why?

Attached sample project to show the issue.

[AnimatedWebPTest.zip](https://github.com/zjupure/GlideWebpDecoder/files/2568396/AnimatedWebPTest.zip)

Also attached video to show issue.

[device-2018-11-10-144519.zip](https://github.com/zjupure/GlideWebpDecoder/files/2568397/device-2018-11-10-144519.zip)

Tested on Pixel 2 with Android P.

**Comment by zjupure** [comment]
Not supported for hook drawable callback. Is there problem when load image into ImageView in normal way?

**Comment by AndroidDeveloperLB** [comment]
@zjupure Please support it (or some alternative solution). The point of Glide isn't just for viewing in ImageView. It's also for loading content, to be shown in any way we desire. For normal (static, non-animated) images, we can always set them to be directly shown on ImageView, but we can also choose that upon finishing loading, we choose what to do with the image.

Using an ImageView doesn't allow to get frame by frame.
Not always we can use ImageView. For example, we can't use views at all in live wallpaper apps.
I don't have this issue on the new ImageDecoder API for example ([here](http://s000.tinyupload.com/?file_id=19449207794739581267)) .

**Comment by AndroidDeveloperLB** [comment]
Might also be used in RemoteView, though I can't think of a scenario for it, other than just for fun...

**Comment by zjupure** [comment]
No plan for those rare cases where drawable cannot be drawn but need animation. If the gif decoder in Glide supports, I would like to investigate, but it also not supported. If ImageDecoder API supports, you can request Google to provided android support library to support your features.

If you only want to draw something into canvas that is not in a View, as a simple way, you can do the following:
*  decode the image into `WebpDrawable` first.
*  the class who hold the canvas implement the `Drawable.Callback` and bind it with `WebpDrawable`
*  start the `WebpDrawable` animation and redraw the frame on Drawable.Callback 
 `invalidateDrawable()` method. Just pass the canvas to `WebpDrawable.draw(canvas)`. You can learn how view and drawable are binded and redraw.

If you want to decode an animated image frame by frame with more advanced control, you should learn how the gif/webp are decoded. See [WebpDecoder](https://github.com/zjupure/GlideWebpDecoder/blob/master/webp_decoder/src/main/java/com/bumptech/glide/integration/webp/decoder/WebpDecoder.java) and [WebpFrameLoader](https://github.com/zjupure/GlideWebpDecoder/tree/master/webp_decoder/src/main/java/com/bumptech/glide/integration/webp/decoder) as reference.
Glide support adding your `ResourceDecoder`. If you like, you can decode the animated image into anything you can define. Following are some tips:
* construct a `GifDecoder/WebpDecoder` from the `ByteBuffer/InputStream`
* you can get the frame count and each frame duration from `GifDecoder/WebpDecoder`, then you can request frame from `GifDecoder/WebpDecoder` and handle the bitmap from SimpleTarget callback.
```
Glide.with(context).load(gifdecoder).into(target);
```
* you can do anything with the recevied frame bitmap. Then delay frame duration, call `GifDecoder/WebpDecoder#advance()` and ready to loadNextFrame().

**Comment by AndroidDeveloperLB** [comment]
But this sounds like what I already did. Look at the sample I've attached. Here's the relevant code for WebP :

                                webpDrawable = drawable
                                val bitmap = Bitmap.createBitmap(drawable.intrinsicWidth, drawable.intrinsicHeight, Bitmap.Config.ARGB_8888)
                                val canvas = Canvas(bitmap)
                                drawable.setBounds(0, 0, bitmap.width, bitmap.height)
                                val originalCallback = drawable.callback
                                drawable.setLoopCount(WebpDrawable.LOOP_FOREVER)
                                drawable.callback = object : Drawable.Callback {
                                    override fun unscheduleDrawable(who: Drawable, what: Runnable) {
                                        originalCallback?.unscheduleDrawable(who, what)
                                    }

                                    override fun invalidateDrawable(who: Drawable) {
                                        originalCallback?.invalidateDrawable(who)
                                        who.draw(canvas)
                                        imageView.setImageBitmap(bitmap)
                                        Log.d("AppLog", "invalidateDrawable ${drawable.frameIndex}/${drawable.frameCount}")
                                    }

                                    override fun scheduleDrawable(who: Drawable, what: Runnable, `when`: Long) {
                                        originalCallback?.scheduleDrawable(who, what, `when`)
                                    }
                                }
                                drawable.start()

It started fine, but if I let the device sleep for a bit, it has the issue I wrote about.

**Comment by zjupure** [comment]
You drawble not bind to a view and so you should start/stop the animation by yourself. When the device sleep some time, the drawable might be recycled by Glide. You can add some log see what happens and why the animation not restart again.

**Comment by AndroidDeveloperLB** [comment]
According to the code of ImageView, I can see that all it does it set a callback, which is what I did.
I've now set the callback to belong to the Activity instead, and it seems that it helped!
Even after minutes of waiting when the device screen was turned off, the animation could resume.

Thank you!

**Comment by AndroidDeveloperLB** [comment]
A nice working sample can be found here, in case you are interested:

[AnimatedWebPTest.zip](https://github.com/zjupure/GlideWebpDecoder/files/2599117/AnimatedWebPTest.zip)
