### ISSUE TITLE
Question: does using GifDrawable/WebpDrawable also cache their frames?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#23]
I've noticed that compared to another solution I got ([here](https://github.com/huzongyao/AndLibNsgif)) for showing Gif animation, this one takes a bit more CPU yet also less RAM .

I've tested on this GIF:
[example2.zip](https://github.com/zjupure/GlideWebpDecoder/files/2597179/example2.zip)

I got a similar comparison results with the new ImageDecoder API of Android P.

Does this mean that using this cool Glide library, it doesn't cache the results, and does the decoding over and over, no matter how much free RAM there is?

If so, is there a way to change this behavior? Maybe let it cache up to certain amount of RAM of my choice?

If it does have caching, how can I enhance it?

Or maybe Glide caches the content of the GIF/WEBP, and then the rest is on the CPU ?

**Comment by zjupure** [comment]
As I known, Glide library won' t cache gif frames result to memory. I think it is a balance of cpu and memory usage. It's hard to decide how many frames of one gif image should be cached. Some gif/webp might contains 100+ frames and many frame bitmaps in gif/webp image are similar with only minor difference. When an app need to display much animated image (gif/webp), caching the frame will cause the bitmap OOM easily. More complicated memory management are required and avoid flush static image caches meanwhile. So the gif/webp frames are always decoded and rendered in a realtime without cache.

You can test more gif/webp images in a screen to get more reliable performance data not just one specifical image.

**Comment by zjupure** [comment]
`AnimatedImageDrawable` render code is in native and I have not investigated it. The memory cache mechaim for frame should be implemented by Glide library. If you have good idea or PR, you can submit feedback to [Glide](https://github.com/bumptech/glide) . Once Glide library support it, this library will follow the changes soon.

**Comment by AndroidDeveloperLB** [comment]
Since I don't have time to investigate how Glide works behind the scenes (let alone its caching mechanism), I only thought that since the caching doesn't exist in this case, and I have a solution for going frame-by-frame (you helped me a bit, here: https://github.com/zjupure/GlideWebpDecoder/issues/22 ) , I could cache some of the bitmaps by myself, outside of the Glide library. Not sure if it's possible. Just an idea.

Do you know perhaps how does the other library do it (from here: https://github.com/huzongyao/AndLibNsgif ) ? Sadly it's not available for animated WEBP, but on animated GIF it uses a bit less CPU than here (though uses a bit more RAM).

**Comment by zjupure** [comment]
I do not known AndLibNsgif library as you mentioned. Glide library not support frame-by-frame cache and there is no easy way to extend the Glide interface or function.

**Comment by AndroidDeveloperLB** [comment]
Too bad. Thank you for your help and kindness !
