### ISSUE TITLE
Question: is it possible to add animated HEIC files support too?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#24]
Or is it too demanding on today's devices, requiring too much CPU ?
Is it even open sourced and allowed to have a decoder to stay on Apache license?

Would you consider adding it?

Here's a sample:
http://nokiatech.github.io/heif/content/image_sequences/starfield_animation.heic

Found from :
http://nokiatech.github.io/heif/examples.html

**Comment by zjupure** [comment]
No plan to support HEIC. For Android P, framework support decoding HEIC natively. For devices before P, there is no suitable open sourced native HEIC decoder written by C/C++.

**Comment by AndroidDeveloperLB** [comment]
For some reason Android P ImageDecoder doesn't return AnimatedImageDrawable for animated HEIC as I've tested, so it can't get animated:
https://issuetracker.google.com/issues/119566797

No idea why.

**Comment by AndroidDeveloperLB** [comment]
Do you know perhaps of an alternative to viewing HEIC files, including animated ones?

**Comment by zjupure** [comment]
If you have time, you can see the project https://github.com/nokiatech/heif. It provides the native Heif reader/writer. What you need to do is wrapping the interface with jni and Java adapter. Then render the decoded bitmaps to canvas.

**Comment by AndroidDeveloperLB** [comment]
Thank you kindly. I hope I will have time for this.
It's not Apache/MIT license, but it seems as permissive. Am I right to assume that it should be fine to use it just as if it's Apache/MIT  ?
