### ISSUE TITLE
Suggestion: remove "buildToolsVersion" from repository

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#25]
The gradle plugin doesn't need it anymore.

**Comment by zjupure** [comment]
Grade plugin just use the minumin buildToolsVesion not the lastest by default. We can specific the latest version released.

**Comment by AndroidDeveloperLB** [comment]
The IDE suggests to remove it. Here's an example:

![image](https://user-images.githubusercontent.com/5357526/48979664-ffc39a00-f0c6-11e8-8420-281a64f67f98.png)


Even when creating a new project, it doesn't have the "buildToolsVersion" anymore. I had to add it myself to show you this suggestion.

Where did you see it uses the minimum? It should use the latest that's available...
Why would the IDE suggest to remove it, if it has a bad decision of what to use?
The whole point is to stop updating it in the projects...

In fact, what I see on the suggestion is that it will use the latest version. If I put an old version, it tells me it will use "28.0.3", even though I have both installed.

If it is indeed using the minimal one, I think it's a bug that should be reported:
https://issuetracker.google.com/issues

I think it's enough to just update the gradle plugin.

**Comment by zjupure** [comment]
This warning is because your buildToolsVersion is lower than the minimum version that your current gradle plugin support. If "28.0.4" is released, you gradle plugin will still use the default version 28.0.3. It is not really care.

**Comment by AndroidDeveloperLB** [comment]
So they need to sync between each other, which occurs anyway as you need to update.
