### ISSUE TITLE
Question: Which libraries exactly does this library use?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#26]
And how do you keep them updated?

Which version of each is used now?

**Comment by AndroidDeveloperLB** [comment]
I mean on which links exactly do you look at? The only one I've found is of framesequence, which is here:

https://android.googlesource.com/platform/frameworks/ex/+/android-9.0.0_r18/framesequence/

**Comment by zjupure** [comment]
There are links in readme. libwebp is here https://github.com/webmproject/libwebp.
Framesequences not used in this library, It have some issues when loading large images.

**Comment by AndroidDeveloperLB** [comment]
It's not used? So why does it exist:

https://github.com/zjupure/GlideWebpDecoder/tree/master/framesequence

?

Is "libwebp " used for GIF too? If not, what is used?

**Comment by zjupure** [comment]
framesequence for just investigation and I have no time to solve some issues. libwebp fro webp images. For gif, you should see libgif. This library won't decode gif image.

**Comment by AndroidDeveloperLB** [comment]
Odd. I was sure it can play GIF, because I've succeeded using it. Maybe Glide has it ? I didn't notice they added it. I thought it was added by using this library ...

**Comment by zjupure** [comment]
Glide support gif playing and it with java decoder not native code for gif. You can see GifDrawable and StandandGifDeocder classes are all in glide library.

**Comment by AndroidDeveloperLB** [comment]
Oh ok, thank you.
So why didn't they add Webp too? Seems just as important...
I hope they also update the gif decoding from time to time.
