### ISSUE TITLE
Question: how to use just the decoding mechanism, without Glide?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#27]
Is it possible to do a manual decoding? To skip between frames?

**Comment by AndroidDeveloperLB** [comment]
But it's also here in the library.
Can't I use the code here for the same purpose?
Also, BTW, "fresco" is a huge library. Takes about 3MB according to what I've found.

**Comment by zjupure** [comment]
The Library is [Apache-2.0-licensed](https://github.com/zjupure/GlideWebpDecoder/blob/master/LICENSE). You can take the code from this library for usage under the LICENSE restriction.

**Comment by AndroidDeveloperLB** [comment]
I mean if it's possible without forking. Which is the main class (or classes) that should be looked at? Does WebP get handled the same way as GIF ?

**Comment by zjupure** [comment]
Sources are open here and you can do everthing you want. No one will tell you how to read the fucking source code.

**Comment by AndroidDeveloperLB** [comment]
I was hoping to use this library to decode even without Glide.
Of course I can read the entire source code, but I think only a part of it is relevant. Some is used very closely to the NDK code, and some to Glide itself.
