### ISSUE TITLE
Question: how to skip to specific frame, to allow handling of configuration change

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#28]
Suppose I play a GIF/WEBP animation, and now I change the orientation.
I don't want the animation to start from the beginning.

I know it's possible to get which is the current frame index, but how can I skip to a specific frame ?

**Comment by zjupure** [comment]
Drawable do not have `onSaveInstance()` method like Activity/View and it is stateless. It is not support for handling configuration change.

**Comment by AndroidDeveloperLB** [comment]
So how can I avoid the animation from being restarted, like a movie?
Only way I can think about is to have configChange in manifest, to ignore it and avoid re-creation of the Activity...
