### ISSUE TITLE
0.0.4cannot use

### ISSUE THREAD

**Issue by kevin-ke** [zjupure/GlideWebpDecoder#3]
0.0.3 is normal,upgrade to 0.0.4,the image do not show and animate.

**Comment by zjupure** [comment]
which glide version are you use? glide 4.2 or 4.4?

**Comment by zjupure** [comment]
0.0.4 version is broken with glide 4.2, it can only work with glide 4.4. If you are use glide 4.2, please try upgrade webpdecoder to 0.0.5.

**Comment by kevin-ke** [comment]
Yes, we use 0.04 with glide 4.2
Another question, when we use 0.03 to animate webp image,  and stay one page  a few minutes, it will crash with jni error , big probability

**Comment by kevin-ke** [comment]
the log as follows:

Build fingerprint: 'Xiaomi/hermes/hermes:5.0.2/LRX22G/8.2.1:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 5386, tid: 5386, name: .android.***  >>> package name <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    r0 00000000  r1 abcb2f58  r2 abf97608  r3 00000000
    r4 abcb2f58  r5 ab543130  r6 00000001  r7 f6a9b298
    r8 00000080  r9 ab161228  sl 24128240  fp 22c08d00
    ip f6a9a80c  sp ff804b40  lr f6a63ba7  pc f6a7f1bc  cpsr 000f0030

backtrace:
    #00 pc 000381bc  /system/lib/libhwui.so (_ZN7android10uirenderer13ResourceCache23decrementRefcountLockedEPK8SkBitmap+7)
    #01 pc 0001cba3  /system/lib/libhwui.so
    #02 pc 0001ccd9  /system/lib/libhwui.so
    #03 pc 00035fd5  /system/lib/libhwui.so (_ZN7android10uirenderer10RenderNode21setStagingDisplayListEPNS0_15DisplayListDataE+20)
    #04 pc 000b189f  /data/dalvik-cache/arm/system@framework@boot.oat
