### ISSUE TITLE
How  controll animator play counts?

### ISSUE THREAD

**Issue by littlezan** [zjupure/GlideWebpDecoder#30]
is there have a way to controll animator play fixed time?

**Comment by zjupure** [comment]
@littlezan you can get the `WebpDrawable` instance from the ImageView when glide load success, and then call `setLoopCount()` method to control the max loop times that animation plays.

```Java
Drawable drawable  = imageView.getDrawable();
if (drawable instanced WebpDrawable) {
    ( (WebpDrawable)drawable).setLoopCount(5);
}
```

**Comment by littlezan** [comment]
thanks
