### ISSUE TITLE
The onFrameReady method in class WebpFrameLoader may have bug

### ISSUE THREAD

**Issue by liusgh** [zjupure/GlideWebpDecoder#34]
In line 209, it is necessary to add the judgment of the flag "isRunning". Since the message of the handler is delayed, the delaytarget still holds a reference to the Bitmap. If there is a view that uses the same Bitmap at this time, it will cause drawing problems such as overlapping images.

**Comment by zjupure** [comment]
Thanks your advice and I will sync the code WebpFrameLoader with GifFrameLoader in glide.
