### ISSUE TITLE
Question: Possible to use old version of Glide with newest version GlideWebpDecoder? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#37]
They say here that Glide performs best on 3.7.0 version of Glide:

https://github.com/bumptech/glide/issues/2471#issuecomment-489448208

And that the newest ones are very bad on it.

**Comment by zjupure** [comment]
No plan to support older version Glide 3.x. You should fire issue to Glide to optimize the image loading.

**Comment by AndroidDeveloperLB** [comment]
Makes sense. 
Is it possible to have a stand-alone decoder for WEBP, then?
On which files of this library should I look, if I want to extract it and not depend on Glide at all ?
