### ISSUE TITLE
Can you support getLoopCount at WebpDrawable

### ISSUE THREAD

**Issue by playNeat** [zjupure/GlideWebpDecoder#38]
I need to get loop count from WebpDrawable.
I just want handle setLoopCount when loop count is too large value or infinite.
But WebpDrawable doesn't have getLoopCount().
Is it available?

**Comment by zjupure** [comment]
It is really care? GifDrawable in glide without this method too.

**Comment by playNeat** [comment]
> It is really care? GifDrawable in glide without this method too.
> 
> WebpDrawable max loop count is loop forever. You might want to get the original loop count in webp image, then judge use it or not?

Yes! I want to setLoopCount about 5, if getLoopCount() returns over 5.
But getLoopCount() returns 1, then webp should place once.
And I will support image click event to replay.

**Comment by zjupure** [comment]
support in 1.6.${GLIDE_VERSION}
