### ISSUE TITLE
播放动图时 内存一直增加

### ISSUE THREAD

**Issue by AlphaBoom** [zjupure/GlideWebpDecoder#39]
播放动态webp的时候native内存占用一直在增加，可以被GC掉。1.5.4.8.0版本。

**Comment by zjupure** [comment]
Yes, it is a truth. It is caused by [webp.cpp#L325](https://github.com/zjupure/GlideWebpDecoder/blob/master/webp_decoder/src/main/jni/webp.cpp#L325)  WebPDemuxGetFrame() in libwebp library will always memset() a new block memory to decode frame data.

If I have time, I will try to investigate it with memory pool or other solution to keep memory stable. PR is also welcome.

**Comment by tuomao** [comment]
找到原因了么？发现用这个库播放webp动图的时候，内存比Fresco几乎高了一倍。

**Comment by zjupure** [comment]
@AlphaBoom @tuomao try 1.6.${GLIDE_VERSION}  it might have been optimized by put bitmap of frame into memory cache. If still have performance issue,  please report to me.

**Comment by AlphaBoom** [comment]
我通过[如下代码](https://gist.github.com/AlphaBoom/a9b52e6a26009182bc5a22de8f78ad90)
使用，依然存在这个问题。
刚启动应用时：
![image](https://user-images.githubusercontent.com/30779939/63823125-524b2300-c985-11e9-918e-1f734019e1cb.png)
放置一段时间：
![image](https://user-images.githubusercontent.com/30779939/63823238-b40b8d00-c985-11e9-9ca4-b95e1c37540f.png)
主动触发GC:
![image](https://user-images.githubusercontent.com/30779939/63823272-d7ced300-c985-11e9-8b6c-d2853f423fd1.png)

**Comment by zjupure** [comment]
看了下，不同的机型表现不太一样，跟了Glide的代码，跟Glide的缓存大小配置有关，Glide默认只缓存了两屏左右的Bitmap，当图片数量或者webp动图帧比较多时，很容易就溢出了。这时候会走到native层去重新渲染解码WebPFrame，libwebp decode frame时开销比较大，申请了临时内存，加上动图播放很多，这样短时间内存碎片增加，不断申请和释放（可以被GC掉）。对比了下Fresco，相同机型使用默认配置Fresco的缓存比Glide大2倍多。Native层不太适合修改libwebp的代码，建议
1. 适当调整Glide的缓存策略，增大内存buffer值
2. webp支持针对单张图片的帧设置缓存策略，默认策略是WebpFrameCacheStrategy.AUTO，利用的是Glide全局缓存池。可修改加载策略为WebpFrameCacheStrategy.ALL，把解码后的帧bitmap全部缓存到Java堆避免重复创建。

```
GlideApp.with(mContext)
                //.asBitmap()
                .load(url)
                .placeholder(R.drawable.image_loading)
                .error(R.drawable.image_error)
                .set(WebpFrameLoader.FRAME_CACHE_STRATEGY, WebpFrameCacheStrategy.ALL)
                .into(imageView);
```

**Comment by AlphaBoom** [comment]
通过调整Glide缓存策略可以解决

**Comment by YouheiLee** [comment]
用的最新代码，仍然出现了此问题。增大了Glide缓存，策略设置成了All，native内存一直缓慢增加。作者可以自行测试一下。我用的手机 OPPO A9，android 9.0
