### ISSUE TITLE
为什么集成了还是不能显示动图

### ISSUE THREAD

**Issue by incomingflyingbrick** [zjupure/GlideWebpDecoder#44]
我按照文档上面的方法集成了，但是还是没法显示动图，只能显示静态的，请问集成之后需要做什么代码改动么？

**Comment by zjupure** [comment]
请参考sample工程，你按照Glide的文档，定义了@GlideModule注解的AppModule了吗

**Comment by incomingflyingbrick** [comment]
@GlideModule 这个我已经加了，我发现图是在动的，但是图动的很卡，如果在一个recycerl view里面加载了很多图，那就卡的不行，几乎和静态的没什么区别。请问这种情况应该怎么处理？谢谢

**Comment by zjupure** [comment]
@incomingflyingbrick 在RecyclerView里播放卡顿，你需要分析下RecyclerView里同时播放的图片数量，当图片滑出屏幕时View是否及时detach，动画相应的停止了。可以用Android Studio的profile看下cpu占用情况，看是播放解码webp引起的，还是有其他heavy的任务在抢占cpu
