### ISSUE TITLE
giflib

### ISSUE THREAD

**Issue by zhenxinchen** [zjupure/GlideWebpDecoder#47]
项目里面有另外一个模块，使用的是giflib，这样使用Glide加载GIF图也可以提升效率，所以为什么不使用这个呢？跟webpdecoder这个模块有做什么对比吗？求告知~

**Comment by zjupure** [comment]
FrameSequence是Android Framework里的一个解码Gif/Webp的库，8.0系统自带的，它依赖了giflib和libwebp库。FrameSequenceDrawable在解码Gif/Webp图片有个使用上的问题，就是不支持缩放和采样，解码出来是整张图片大小，而不能根据View的大小设置采样比，引入的问题就是在Android上容易出现OOM。要支持这个feature，还不太好改，还不如直接用libwebp自己包装。因此这个module目前不在维护和输出。

Glide本身支持Gif加载，使用Java解码器实现的，WebpDecoder这个库主要解决的是webp动画播放的问题，没有实现Gif图片的加载，Gif加载效率这块也没有做深入分析。感兴趣的话，可以自己基于giflib给Glide实现一套解码器，注入到Glide中就可以。同样需要解决的问题，就是能够按View控件的大小来解码Gif的帧。
