### ISSUE TITLE
同时使用多种Transform

### ISSUE THREAD

**Issue by Techck** [zjupure/GlideWebpDecoder#48]
我想要同时使用圆角和CropCenter，没效果，demo只使用了一个，请问现在的版本能否支持使用多个Transform？

**Comment by zjupure** [comment]
Transformation<Bitmap> trans = new MultiTransformation<>(new CenterCrop(), new RoundedCorners(20));
WebpDrawableTransformation webpTrans =new WebpDrawableTransformation(trans);
试下先构造MultiTransformation，然后用WebpDrawableTransformation wrapper下？
