### ISSUE TITLE
Webp的动图只能使用ARGB_888这种方法加载吗？

### ISSUE THREAD

**Issue by MerlinYu** [zjupure/GlideWebpDecoder#49]
WebpDecoder
```
    /** @Override Added in Glide 4.4.0 */
    public void setDefaultBitmapConfig(Bitmap.Config config) {
        if (config != Bitmap.Config.ARGB_8888) {
            throw new IllegalArgumentException("Unsupported format: " + config
                    + ", must be one of " + Bitmap.Config.ARGB_8888);
        }

        mBitmapConfig = config;
    }
```

**Comment by zjupure** [comment]
看了下libwebp库底层是支持RGB_565解码的，需要把config信息传递下去，目前没有实现

**Comment by MerlinYu** [comment]
> 看了下libwebp库底层是支持RGB_565解码的，需要把config信息传递下去，这个要求webp动画中不含有透明的帧，目前没有实现

**Comment by MerlinYu** [comment]
我看了源码，从上层不支持config信息传递，我们的项目大量使用到webp的动态，想优化一下这化图片的内存占用 @zjupure

**Comment by zjupure** [comment]
https://github.com/zjupure/GlideWebpDecoder/blob/master/webp_decoder/src/main/jni/webp.cpp#L482
@MerlinYu native层核心decode代码在`WebPFrame_nativeRenderFrame()`里，传递的Bitmap里有config信息，可以从这里读到解码的格式，然后配置webp的decode参数，解码/渲染等地方需要修改，感兴趣可以先尝试修改下

**Comment by zjupure** [comment]
本地修改试了下，webp动画两个关键帧之间几乎都是带alpha通道的，使用RGB_565解码会丢失信息，导致渲染画面时失真。

**Comment by MerlinYu** [comment]
@zjupure 我Fork 了代码，然后试了确实使用RGB_565会丢失信息，但是使用ARGB_4444可以正常解析。
与Glide绑定使用的话，能否考虑将config的设置接口暴露出来？

**Comment by ksc91u** [comment]
請問一下這個問題有解嗎？
剛剛測試了最新版的還是沒有透明度

使用範例的這個檔案
https://qidian.qpic.cn/qidian_common/349573/a36f7d7d8a5e15e1cf3c32d05109467a/0

謝謝

**Comment by zjupure** [comment]
@ksc91u 这个有什么问题，可以正常渲染，背景就是透明的，你可以修改ImageView的背景色验证

**Comment by ksc91u** [comment]
不好意思是我犯傻了, 的確看到的是 ImageView 的背景色, 改成透明就好了, 感謝大大
