### ISSUE TITLE
Stopped Webp drawable in recyclerview get distorted

### ISSUE THREAD

**Issue by nonla** [zjupure/GlideWebpDecoder#5]
I have a list of webp images in recycler view.
Each of webp image is displayed fine, the scrolling is very smooth. There is only 1 problem.
When I stop a webp drawable, then scroll the list, the stopped webp drawable get distorted and sometimes it displays other webp drawable in the list.

![device-2018-06-09-193529 1](https://user-images.githubusercontent.com/3670153/41191637-caa95a5a-6c1c-11e8-9105-cbc842670f0c.gif)

The code that I use to stop/start the webp.
```
                    Drawable drawable = mIvGif.getDrawable();
                    if (drawable instanceof Animatable) {
                        Animatable animation = (Animatable) drawable;
                        if (animation.isRunning()) {
                            animation.stop();
                        } else {
                            animation.start();
                        }
                    }
```

**Comment by zjupure** [comment]
can you provide a sample project to reproduce this issue? Or can you modify the sample to fill it out? Does it related about the webp images?

**Comment by zjupure** [comment]
I think this issue should have been solved and it's caused by WebpDecoder bitmap cache and Glide bitmap pool cache conflct. Please update to version 1.0 for a taste.
