### ISSUE TITLE
webpdrawable动画restart

### ISSUE THREAD

**Issue by ccccmmmz** [zjupure/GlideWebpDecoder#59]
我们项目中使用了缓存 ,因为好多webp动画要重复使用,所以glide那边是skipmemory.我们这边做法是手动调用webpdrawable的start相关方法,但是发现WebpFrameLoader.loadNextFrame中的isLoadPending为true会return调用链.目前这边的问题是 比如说我准备连续播放5次动画,第一次走glide的load是正常显示,第二次就不显示,第三次就会显示动画.直接走缓存的话,比如说lru也是隔次显示,另外希望可以将webpdrawble的start stop方法接口开放回调,或者说作者能添加一个restart的方法入口吗,或者是
WebpFrameLoader里面的变量暴露出来,我尝试了反射,可能我水平有限 暂时没获取到.可能描述的有点乱,见谅

**Comment by zjupure** [comment]
没太理解你的需求场景，如果是想控制播放次数，可以调用setLoopCount(times)设置，如果想要手动控制restart的时机，可以注册AnimationCallback监听动画播放结束事件后重新调用start

**Comment by ccccmmmz** [comment]
我刚看了下,4.8版本的是Animatable实现 最近版是Animatable2实现,不改变版本的情况下有方法吗,我们这个是组件,外部依赖的主包是4.8版本的Glide

**Comment by zjupure** [comment]
升级该库到1.6.4.8.0，有注册AnimationCallback的接口。

**Comment by ccccmmmz** [comment]
好了 谢谢

**Comment by ccccmmmz** [comment]
这边比如说 setloopCount(1)
animationEnd之后我还想播放这个动画,有没有可行的方案,
我在end之后再次调用start还有startfromfirst都试过不可以

**Comment by zjupure** [comment]
@ccccmmmz sorry for reply this issue later. I have time to investigate this issue, it is because the animationEnd callback is triggered before stop() method. You can restart the animation by post this call for start to next frame, It can works.

```
@Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        final WebpDrawable webpDrawable = (WebpDrawable)resource;
                        webpDrawable.setLoopCount(1);
                        webpDrawable.registerAnimationCallback(new Animatable2Compat.AnimationCallback() {
                            @Override
                            public void onAnimationEnd(Drawable drawable) {
                                super.onAnimationEnd(drawable);
                                new Handler(Looper.getMainLooper()).post(new Runnable() {
                                    @Override
                                    public void run() {
                                        webpDrawable.start();
                                    }
                                });
                            }
                        });

                        return false;
                    }
```
