### ISSUE TITLE
RecyclerView瀑布流加载webp Gif图片异常

### ISSUE THREAD

**Issue by Papaddington** [zjupure/GlideWebpDecoder#61]
### 问题描述
由于瀑布流中图片高度的不确定性, 需要根据后台图片比例动态改变imageView的高度;

在该种情况下加载WebP格式gif时出现图片一直变大变小的现象,感觉可能是gif每个drawabale高度不一致的原因

另外为了定位问题,测试了一下普通gif格式的图片没有出现上述问题,麻烦聚聚看一下这个问题
#### Glide
4.11.0
#### GlideWebpDecoder
1.8.4.11.0

#### 机型 
小米9
#### android版本
android10

**Comment by zjupure** [comment]
can you provide some sample code to reproduce this issue and video capture?

**Comment by Papaddington** [comment]
> can you provide some sample code to reproduce this issue and video capture?

I am writing the sample code. Please send me your email address so that I can send the sample project and video capture to you

**Comment by zjupure** [comment]
@Papaddington You can send your sample project to zjupure@gmail.com, I will take a look at after work.

**Comment by Papaddington** [comment]
@zjupure Sry, the reason for this bug is due to the screen adaptation of my project. But I don't know why this problem only occurs when using webp format. Can you help me take a look? I have sent the sample to your mailbox.

**Comment by zjupure** [comment]
@Papaddington 看了下demo复现后初步调试分析，发现是LruBitmapPool在reuse Bitmap过程中glide会复用比所需width*height大的图，然后调用reconfigure()导致了渲染异常，可能跟Android Q上bitmap底层某些改动有关。目前可以通过替换LruBitmapPool的strategy来workaround解决下

**Comment by lvzhiwei0221** [comment]
您好，这个bug，我看您提交修复了，但是好像依然有这个问题。我用的是最新的。手机也是Q的 小米9.瀑布流的情况下，图片偶尔还会忽大忽小

**Comment by Papaddington** [comment]
@lvzhiwei0221 我尝试了作者的方法,在Glidemodule中反射替换LruBitmapPool 可以临时解决这个bug.之前复现的机型已经没问题了

**Comment by lvzhiwei0221** [comment]
> @lvzhiwei0221 我尝试了作者的方法,在Glidemodule中反射替换LruBitmapPool 可以临时解决这个bug.之前复现的机型已经没问题了

您好，感谢您的回答，不过我有点没有明白具体操作，您可以细化一下需要怎么做嘛。谢谢了

**Comment by Papaddington** [comment]
@lvzhiwei0221 可以参考作者最新一次commit 或者 临时参考一下项目中的GlideModule, demo地址https://github.com/Papaddington/WebpSample

**Comment by zjupure** [comment]
> 您好，这个bug，我看您提交修复了，但是好像依然有这个问题。我用的是最新的。手机也是Q的 小米9.瀑布流的情况下，图片偶尔还会忽大忽小

修改没有经过充分测试验证，APP接入层可以在AppGlideModule的applyOptions中参考com.bumptech.glide.integration.webp.decoder.Utils的实现修改LruBitmapPool

**Comment by lvzhiwei0221** [comment]
> > 您好，这个bug，我看您提交修复了，但是好像依然有这个问题。我用的是最新的。手机也是Q的 小米9.瀑布流的情况下，图片偶尔还会忽大忽小
> 
> 修改没有经过充分测试验证，APP接入层可以在AppGlideModule的applyOptions中参考com.bumptech.glide.integration.webp.decoder.Utils的实现修改LruBitmapPool

好的，感谢

**Comment by lvzhiwei0221** [comment]
> @lvzhiwei0221 可以参考作者最新一次commit 或者 临时参考一下项目中的GlideModule, demo地址https://github.com/Papaddington/WebpSample

好的，感谢

**Comment by lvzhiwei0221** [comment]
按照题主，还有作者的方法都做了，我这里还是会有问题。作者有时间修复好记得@一下。我替换下版本更新。项目有点紧，排查有点吃紧。thanks

**Comment by Papaddington** [comment]
@lvzhiwei0221 兄弟 你没有开glide注解调试器

**Comment by lvzhiwei0221** [comment]
加注解了啊，也在gradle中添加了注解的那个引用。glide可以找到新写的glidemoudle------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Paddington&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月23日(星期二) 晚上7:39
收件人:&nbsp;&quot;zjupure/GlideWebpDecoder&quot;<GlideWebpDecoder@noreply.github.com&gt;;
抄送:&nbsp;&quot;lvzhiwei0221&quot;<290243232@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [zjupure/GlideWebpDecoder] RecyclerView瀑布流加载webp Gif图片异常 (#61)

**Comment by zjupure** [comment]
@lvzhiwei0221 这个Demo https://github.com/Papaddington/WebpSample在你那边设备还是不行吗？能提供下机型和复现demo？

**Comment by lvzhiwei0221** [comment]
> @lvzhiwei0221 这个Demo https://github.com/Papaddington/WebpSample 在你那边设备还是不行吗？能提供下机型和复现demo？

您可以加下我都qq吗？14492994。我GlideMoudule是这样写的，只实现applyOptions方法或者registerComponents，还有两个方法同时实现，都不能解决问题。

import android.content.Context;
import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.drawable.BitmapDrawable;
import android.os.Build;

import androidx.annotation.RequiresApi;

import com.bumptech.glide.Glide;
import com.bumptech.glide.GlideBuilder;
import com.bumptech.glide.Registry;
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.integration.webp.decoder.AnimatedWebpBitmapDecoder;
import com.bumptech.glide.integration.webp.decoder.ByteBufferAnimatedBitmapDecoder;
import com.bumptech.glide.integration.webp.decoder.ByteBufferBitmapWebpDecoder;
import com.bumptech.glide.integration.webp.decoder.ByteBufferWebpDecoder;
import com.bumptech.glide.integration.webp.decoder.StreamAnimatedBitmapDecoder;
import com.bumptech.glide.integration.webp.decoder.StreamBitmapWebpDecoder;
import com.bumptech.glide.integration.webp.decoder.StreamWebpDecoder;
import com.bumptech.glide.integration.webp.decoder.WebpDownsampler;
import com.bumptech.glide.integration.webp.decoder.WebpDrawable;
import com.bumptech.glide.integration.webp.decoder.WebpDrawableEncoder;
import com.bumptech.glide.load.engine.bitmap_recycle.ArrayPool;
import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool;
import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPoolAdapter;
import com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool;
import com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy;
import com.bumptech.glide.load.engine.cache.MemorySizeCalculator;
import com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder;
import com.bumptech.glide.module.AppGlideModule;

import org.jetbrains.annotations.NotNull;

import java.io.InputStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.nio.ByteBuffer;

import kotlin.jvm.internal.Intrinsics;

@GlideModule
public class WebpGlideModule extends AppGlideModule {

    private static boolean USE_COMPACT_POOL_ON_Q = false;

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        super.applyOptions(context, builder);
        MemorySizeCalculator memorySizeCalculator = (new MemorySizeCalculator.Builder(context)).build();
        Intrinsics.checkExpressionValueIsNotNull(memorySizeCalculator, "memorySizeCalculator");
        int size = memorySizeCalculator.getBitmapPoolSize();
        BitmapPool tempBitmapPool;
        if (size > 0) {
            LruBitmapPool pool = new LruBitmapPool((long)size);
            this.fixBitmapPoolStrategy(pool);
            tempBitmapPool = (BitmapPool)pool;
        } else {
            tempBitmapPool = (BitmapPool)(new BitmapPoolAdapter());
        }

        BitmapPool bitmapPool = tempBitmapPool;
        builder.setMemorySizeCalculator(memorySizeCalculator);
        builder.setBitmapPool(bitmapPool);
    }


    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {

        // We should put our decoder before the build-in decoders,
        // because the Downsampler will consume arbitrary data and make the inputstream corrupt
        // on some devices
        final Resources resources = context.getResources();
        final BitmapPool bitmapPool = glide.getBitmapPool();
        final ArrayPool arrayPool = glide.getArrayPool();
        // fix strategy on Android Q
        final BitmapPool webpBitmapPool = getCompactBitmapPool(bitmapPool);
        /* static webp decoders */
        WebpDownsampler webpDownsampler = new WebpDownsampler(registry.getImageHeaderParsers(),
                resources.getDisplayMetrics(), webpBitmapPool, arrayPool);
        AnimatedWebpBitmapDecoder bitmapDecoder = new AnimatedWebpBitmapDecoder(arrayPool, webpBitmapPool);
        ByteBufferBitmapWebpDecoder byteBufferBitmapDecoder = new ByteBufferBitmapWebpDecoder(webpDownsampler);
        StreamBitmapWebpDecoder streamBitmapDecoder = new StreamBitmapWebpDecoder(webpDownsampler, arrayPool);
        /* animate webp decoders */
        ByteBufferWebpDecoder byteBufferWebpDecoder =
                new ByteBufferWebpDecoder(context, arrayPool, webpBitmapPool);
        registry
                /* Bitmaps for static webp images */
                .prepend(Registry.BUCKET_BITMAP, ByteBuffer.class, Bitmap.class, byteBufferBitmapDecoder)
                .prepend(Registry.BUCKET_BITMAP, InputStream.class, Bitmap.class, streamBitmapDecoder)
                /* BitmapDrawables for static webp images */
                .prepend(
                        Registry.BUCKET_BITMAP_DRAWABLE,
                        ByteBuffer.class,
                        BitmapDrawable.class,
                        new BitmapDrawableDecoder<>(resources, byteBufferBitmapDecoder))
                .prepend(
                        Registry.BUCKET_BITMAP_DRAWABLE,
                        InputStream.class,
                        BitmapDrawable.class,
                        new BitmapDrawableDecoder<>(resources, streamBitmapDecoder))
                /* Bitmaps for animated webp images*/
                .prepend(Registry.BUCKET_BITMAP, ByteBuffer.class, Bitmap.class, new ByteBufferAnimatedBitmapDecoder(bitmapDecoder))
                .prepend(Registry.BUCKET_BITMAP, InputStream.class, Bitmap.class, new StreamAnimatedBitmapDecoder(bitmapDecoder))
                /* Animated webp images */
                .prepend(ByteBuffer.class, WebpDrawable.class, byteBufferWebpDecoder)
                .prepend(InputStream.class, WebpDrawable.class, new StreamWebpDecoder(byteBufferWebpDecoder, arrayPool))
                .prepend(WebpDrawable.class, new WebpDrawableEncoder());
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }


    public static BitmapPool getCompactBitmapPool(BitmapPool bitmapPool) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
            return bitmapPool;
        }

        if (!USE_COMPACT_POOL_ON_Q) {
            return bitmapPool;
        }

        if (bitmapPool instanceof LruBitmapPool) {
            LruBitmapPool oldPool = (LruBitmapPool)bitmapPool;
            long poolSize = (long)(oldPool.getMaxSize() * 1.0f / 3.0f);
            LruBitmapPool newPool = new LruBitmapPool(poolSize);
            try {
                Field field = newPool.getClass().getDeclaredField("strategy");
                field.setAccessible(true);
                Object strategy = field.get(newPool);
                if (strategy instanceof SizeConfigStrategy) {
                    Object newStrategy = getDefaultStrategy();
                    if (newStrategy != null) {
                        field.set(newPool, newStrategy);
                        return newPool;
                    }
                }
            } catch (NoSuchFieldException | IllegalAccessException e) {
                e.printStackTrace();
            }
        }
        return bitmapPool;
    }

    @RequiresApi(api = Build.VERSION_CODES.KITKAT)
    private static Object getDefaultStrategy() {
        String clsName = SizeConfigStrategy.class.getName();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            clsName = "com.bumptech.glide.load.engine.bitmap_recycle.AttributeStrategy";
        } else if (Build.VERSION.SDK_INT < Build.VERSION_CODES.KITKAT) {
            clsName = "com.bumptech.glide.load.engine.bitmap_recycle.AttributeStrategy";
        }

        try {
            Class<?> clazz = Class.forName(clsName);
            Constructor<?> constructor = clazz.getDeclaredConstructor();
            constructor.setAccessible(true);

            return constructor.newInstance();
        } catch (ClassNotFoundException | NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalAccessException | InstantiationException | InvocationTargetException e) {
            e.printStackTrace();
        }
        return null;
    }


    public final boolean fixBitmapPoolStrategy(@NotNull LruBitmapPool bitmapPool) {
        Intrinsics.checkParameterIsNotNull(bitmapPool, "bitmapPool");
        if (Build.VERSION.SDK_INT < 29) {
            return false;
        } else {
            try {
                Field temp = bitmapPool.getClass().getDeclaredField("strategy");
                Intrinsics.checkExpressionValueIsNotNull(temp, "bitmapPool.javaClass.getDeclaredField(\"strategy\")");
                Field field = temp;
                field.setAccessible(true);
                Object strategy = field.get(bitmapPool);
                if (strategy instanceof SizeConfigStrategy) {
                    Object newStrategy = this.getDefaultStrategy();
                    if (newStrategy != null) {
                        field.set(bitmapPool, newStrategy);
                        return true;
                    }
                }
            } catch (NoSuchFieldException var5) {
                var5.printStackTrace();
            } catch (IllegalAccessException var6) {
                var6.printStackTrace();
            }

            return false;
        }
    }
}
