### ISSUE TITLE
same webp url

### ISSUE THREAD

**Issue by wss991** [zjupure/GlideWebpDecoder#62]
Two views show the same webp link, one start and one stop. In recyclerview, slide up and down, and the display image of the stop view will change

**Comment by zjupure** [comment]
I dont understand the issue. Can you provide the video capture, and describe more detail? or show some sample code?

**Comment by wss991** [comment]
![QQ图片20200702184134](https://user-images.githubusercontent.com/17445635/86349539-e1a32000-bc93-11ea-8913-35e33abbe820.jpg)
![QQ图片20200702184604](https://user-images.githubusercontent.com/17445635/86349821-54140000-bc94-11ea-9b3d-0aecdec2160a.jpg)
![QQ图片20200702184610](https://user-images.githubusercontent.com/17445635/86349835-58401d80-bc94-11ea-9e30-7c6820bd2d3b.jpg)

 The first start(), the second doesn't play, then swipe, and the second picture changes

**Comment by wss991** [comment]
private void loadImageWithTransformation(final ImageView imageView, String url, final boolean istrue) {
        if (url.equals(imageView.getTag())) {
            Log.e(TAG, "loadImageWithTransformation: url 相等"+url);
        }
        imageView.setTag(url);

        if (imageView.getDrawable()!= null ) {
            if (imageView.getDrawable() instanceof WebpDrawable){
                WebpDrawable webp= (WebpDrawable) imageView.getDrawable();
                Log.e(TAG, "WebpDrawable webp : "+webp.hashCode() );
                Log.e(TAG, "WebpDrawable  imageview: "+imageView.hashCode() );
                if (istrue) {
                    webp.start();
                } else {
                    webp.stop();
                }
                return;
            }


        }
        CustomViewTarget target = new CustomViewTarget<ImageView, Drawable>(imageView) {
            @Override
            public void onLoadFailed(@Nullable Drawable errorDrawable) {

            }

            @Override
            public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                Log.e(TAG, "onResourceReady hashcode: " + this.getView().hashCode());
                Log.e(TAG, "onResourceReady isTrue: " + istrue);
                if (resource instanceof WebpDrawable) {
                    Log.e(TAG, "WebpDrawable webp : "+resource.hashCode() );
                    this.getView().setImageDrawable(resource);

                }
            }

            @Override
            protected void onResourceCleared(@Nullable Drawable placeholder) {

            }
        };
        GlideApp.with(mContext)
                //.asBitmap()
                .load(url)
                .placeholder(R.drawable.image_loading)
                .error(R.drawable.image_error)

                //.set(WebpFrameLoader.FRAME_CACHE_STRATEGY, WebpFrameCacheStrategy.AUTO)

                .into(target);
    }

**Comment by zjupure** [comment]
The same url will reuse the same decoder like GifDrawable, it works as expected in Glide cache.
