### ISSUE TITLE
why the method "decode" of ByteBufferWebpDecoder only called once

### ISSUE THREAD

**Issue by VincentJin-91** [zjupure/GlideWebpDecoder#63]
when i have two ImageView with same width and height ,and load same resource ID for webp . the method "decode" of ByteBufferWebpDecoder only called once.  so i get only one WebpDrawable .  then two imageview shared one WebpFrameLoader, that cause a error display on my screen.  if the imageviews has different size，the display is correct。。。。

**Comment by zjupure** [comment]
see #62 , works as espected with GifDrawable
