### ISSUE TITLE
加载webp很大几率会出现图片抖动。

### ISSUE THREAD

**Issue by gejiashu** [zjupure/GlideWebpDecoder#64]
看了一下，可能是解码生成的每一帧的图片有问题。
![image](https://user-images.githubusercontent.com/7670817/87289679-87297f80-c52f-11ea-93d1-fb93e596a6f2.png)
发现在这里返回的每一帧的图片是有问题的。

[8474956e5b29d22dbf8945c2f2d81d0f.zip](https://github.com/zjupure/GlideWebpDecoder/files/4911590/8474956e5b29d22dbf8945c2f2d81d0f.zip)
压缩包里面是视频，可以看到是返回的每一帧的图片有问题。
使用的版本是1.8.4.11.0

**Comment by zjupure** [comment]
@gejiashu 解码有问题的机型和系统是？

**Comment by gejiashu** [comment]
试了好几个机型都有问题，看到是WebpDecoder getNextFrame这个方法返回的bitmap就是有问题的。具体原因还没定位到。

**Comment by gejiashu** [comment]
[vcr-34.zip](https://github.com/zjupure/GlideWebpDecoder/files/4912745/vcr-34.zip)
这个是我使用的wepb文件，你可以试试看。这个问题我之前也遇到过。拿一张普通的图片和这张webp多切换几次就出现了。

**Comment by gejiashu** [comment]
看到issue里面有一个recyclerview瀑布流的问题，不知道是不是跟我这个是同一个问题。这个问题是在我手上的三星s9 8.0 和google pixel 10.0上面都有出现的，我这边已经定位到原因了。

导致这个问题的原因是WebpDecoder这个类里面通过，BitmapProvider obtain的bitmap 的density可能会出现不一致的情况。
![image](https://user-images.githubusercontent.com/7670817/87372515-50e51200-c5ba-11ea-9c43-38f7e3fdf094.png)
通过测试在三星s9上面会出现canvas的density是614 而frameBitmap的density是640的情况。我上面提供的webp文件一共有两帧，在手机上还会出现这两帧的frameBitmap 的density不一样的情况，所以就出现了，我视频录制的抖动的问题。

发现在BitmapProvider obtain bitmap之后，统一设置一下bitmap的density可以解决这个问题。

 Bitmap bitmap = mBitmapProvider.obtain(downsampledWidth, downsampledHeight, Bitmap.Config.ARGB_8888);
 bitmap.setDensity(DisplayMetrics.DENSITY_DEVICE_STABLE);

在WebDecoder这个类的所有的BitmapProvider obtain代码后面动态设置一下bitmap的density，就没问题了。

**Comment by zjupure** [comment]
@gejiashu 感谢你的分析，我抽空验证下
