### ISSUE TITLE
.centerCrop() can not work

### ISSUE THREAD

**Issue by zijinzhiyun** [zjupure/GlideWebpDecoder#8]
GlideApp.with(this)
                .load("http://hbpic-10057247.file.myqcloud.com/emoji/shanmeng/0c31ffcaf7ad7ece0d7c7b1e999f76a9.webp")
                .centerCrop()
                .into(mImageView);

java.lang.IllegalArgumentException(Unable to convert com.bumptech.glide.integration.webp.decoder.WebpDrawable@9240340 to a Bitmap)
                                                                              call GlideException#logRootCauses(String) for more detail
                                                                               Cause (1 of 1): class java.lang.IllegalArgumentException: Unable to convert com.bumptech.glide.integration.webp.decoder.WebpDrawable@9240340 to a Bitmap

**Comment by zjupure** [comment]
@zijinzhiyun  Animated webp are construct by multi frame bitmaps. WebpDrawable is drawable not a Bitmap, so we cannot transfrom between WebpDrawable and Bitmap. We can provide our own `WebpDrawableTransfromation` to wrap the original BitmapTransform to implement the sample effect just like Glide build-in `GifDrawableTransformation`

```Java
Transformation<Bitmap> circleCrop = new CircleCrop();
GlideApp.with(mContext)
                .load(url)
                .optionalTransform(circleCrop)
                .optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(circleCrop))
                .into(imageView);
```

Please update this library verison to 1.0 and fix the issue. See samples for detail. Thanks.
