### ISSUE TITLE
Webp animation lagging in RecyclerView

### ISSUE THREAD

**Issue by senthilmca44** [zjupure/GlideWebpDecoder#81]
Hi Team,
               When we are using quality animated webp images in recyclerview, the animation is very laggy.Need help in this

**Comment by zjupure** [comment]
webp decoding is cpu costing, you can cache the decoded bitmap in the memory and it will cost more memory

**Comment by zjupure** [comment]
You can set option WebpFrameLoader.FRAME_CACHE_STRATEGY to ALL when load webp images and it will cache every frame in memory.

 ```
GlideApp.with(mContext)
          .load(url)
          .placeholder(R.drawable.image_loading)
          .error(R.drawable.image_error)
          .set(WebpFrameLoader.FRAME_CACHE_STRATEGY, WebpFrameCacheStrategy.ALL)
          .into(imageView);
```
