### ISSUE TITLE
glide load 使用了override加载就会失败

### ISSUE THREAD

**Issue by ccccmmmz** [zjupure/GlideWebpDecoder#82]

**Comment by zjupure** [comment]
没明白这是什么问题，sample工程有问题吗

**Comment by ccccmmmz** [comment]
GlideApp.with(mContext)
        .load(url)
        .optionalTransform(circleCrop)
        .optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(circleCrop))
        .into(imageView);
就是这里面如果使用了override()就会失败

**Comment by ccccmmmz** [comment]
1.6.4.8.0可以怎么可以加载指定size的webp嘛 就是使用override()属性

**Comment by zjupure** [comment]
> GlideApp.with(mContext)
> .load(url)
> .optionalTransform(circleCrop)
> .optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(circleCrop))
> .into(imageView);
> 就是这里面如果使用了override()就会失败

在sample工程里试了下，没有发现有问题，可以指定解码的图像size
```
GlideApp.with(mContext)
                //.asBitmap()
                .load(url)
                .placeholder(R.drawable.image_loading)
                .error(R.drawable.image_error)
                .optionalTransform(mBitmapTrans)
                .optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(mBitmapTrans))
                .override(300, 300)
                .into(imageView);
```
