### ISSUE TITLE
How write file webp animation 

### ISSUE THREAD

**Issue by ianmsfvenom** [zjupure/GlideWebpDecoder#84]
I try this but write file without animation
```
Glide.with(getContext())
.load(url)
.timeout(50000)
.optionalTransform(centerCrop)
.optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(centerCrop))
.into(img);
```
I tried to put it to bitmap but gave the same result

**Comment by zjupure** [comment]
it is a webp decoder and displayer. what is your meaning about writing webp animation? It is not a webp encoder

**Comment by ianmsfvenom** [comment]
I already got it, don't need it anymore

**Comment by CrackerKSR** [comment]
> I already got it, don't need it anymore

Di you get solutionfor encoing into animated webp? please share
