### ISSUE TITLE
加载出来是静图

### ISSUE THREAD

**Issue by wangfeigit** [zjupure/GlideWebpDecoder#86]
加载的方法：
Transformation<Bitmap> circleCrop = new CircleCrop();
        WebpDrawableTransformation webpDrawableTransformation = new WebpDrawableTransformation(circleCrop);
        GlideApp.with(imageView)
                .asDrawable()
                .load(url)
                .transition(DrawableTransitionOptions.withCrossFade(80))
                .apply(new RequestOptions().priority(Priority.IMMEDIATE))
                .placeholder(resource)
                .error(resource)
                .format(DecodeFormat.PREFER_RGB_565)
                .optionalTransform(circleCrop)
                .optionalTransform(WebpDrawable.class, webpDrawableTransformation)
//                .transform(RoundedCorners(1))
                .into(imageView);

**Comment by zjupure** [comment]
试了下，.transition(DrawableTransitionOptions.withCrossFade(80))这个option引起的，WebpDrawable本身是动画不支持transition操作
