### ISSUE TITLE
Some animated WebP images are broken when applying transformations

### ISSUE THREAD

**Issue by alvingao** [zjupure/GlideWebpDecoder#9]
When applying transformations to some animated WebP images, the result animation looks broken.

For example, with the following code:
```
Glide.with(this)
        .load("https://mathiasbynens.be/demo/animated-webp-supported.webp")
        .apply(new RequestOptions().optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(new CircleCrop())))
        .into(imageView);
```
```
// Dependencies
def GLIDE_VERSION = "4.7.1"
implementation "com.zlc.glide:webpdecoder:0.0.8.${GLIDE_VERSION}"
implementation "com.github.bumptech.glide:glide:${GLIDE_VERSION}"
annotationProcessor "com.github.bumptech.glide:compiler:${GLIDE_VERSION}"
```

The result looks like this:

![glide_webp_decoder_demo](https://user-images.githubusercontent.com/3000575/44143762-823f0aba-a0b7-11e8-8b83-719b333c419f.gif)

Without applying transformations, the images are ok and the animation looks perfect.

**Comment by alvingao** [comment]
I'm aware that the ```WebpDrawableTransformation``` class has an **_unstable_** warning in the code comment, but transformations are required for my use case, so I looked into this.

The problem has nothing to do with the ```WebpDrawableTransformation``` class itself, but is caused by the way ```WebpDecoder``` handles its frame bitmap cache.

When transformations are applied, the original bitmap returned by ```WebpDecoder#getNextFrame()``` might be put back into the bitmap pool, and shouldn't be used any more. But in the ```getNextFrame()``` method, it's also cached into ```mFrameBitmapCache``` and used later, which is why the result looks broken.

I have a fix that caches a new copy of the bitmap into the frame cache and solves the problem. I will create a pull request soon.

**Comment by zjupure** [comment]
@alvingao This is a known issue. Thanks for your investigation and solution. I have verified your PR and it works fine. I will merge it into the respository.
