### ISSUE TITLE
ImageView宽高为wrap_content时webp动图问题

### ISSUE THREAD

**Issue by Android-Mainli** [zjupure/GlideWebpDecoder#91]
ImageView宽设置wrap_content时 直接这样加载webp 动图动画没有执行 指定确定宽高时播放正常
Glide.with(ImageView).load(“xxx”).into(ImageView);

临时解决重写ImageView#onSizeChanged方法  ，期望可以尽快修复
@Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        if (mIsDynamicWebP) {
            //修复在ImageView设置 wrap_content 时宽高不定 导致webp动画无法正常播放
            ViewGroup.LayoutParams layoutParams = getLayoutParams();
            if (layoutParams.width != w || layoutParams.height != h) {
                layoutParams.height = h;
                layoutParams.width = w;
                setLayoutParams(layoutParams);
            } else {
                super.onSizeChanged(w, h, oldw, oldh);
            }
        } else {
            super.onSizeChanged(w, h, oldw, oldh);
        }
    }

**Comment by zjupure** [comment]
在Sample工程里试一下，使用wrap_content加载没问题，有出错的webp图片吗

**Comment by Android-Mainli** [comment]
![test](https://user-images.githubusercontent.com/16352477/150776368-483c9cef-014b-4751-be23-fa35941e5fa7.png)
修改后缀为webp  文件放sdcard 以File形式让Glide加载

**Comment by zjupure** [comment]
把webp文件放在Sample工程里加载没有问题
