### ISSUE TITLE
Request: update Glide version

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zjupure/GlideWebpDecoder#93]
It can be upgraded to 4.13.1 ....

**Comment by zjupure** [comment]
library 2.0.4.13.1 for glide has published in MavenCentral and fix in [330a17c](https://github.com/zjupure/GlideWebpDecoder/commit/330a17c28c8f03f54f28080e63eec314fe1c84be)

**Comment by AndroidDeveloperLB** [comment]
Thank you. I can use it already via gradle?
