### ISSUE TITLE
Needs to support 4.13.2

### ISSUE THREAD

**Issue by Lingviston** [zjupure/GlideWebpDecoder#96]
New version of Glide is available and webp decoder should support it. Would you mind bumping the version and publishing new build?

**Comment by zjupure** [comment]
library 2.0.4.13.2 version has be publish to [MavenCentral](https://search.maven.org/search?q=a:webpdecoder).

**Comment by AndroidDeveloperLB** [comment]
@zjupure I don't get how to use this on gradle file anymore. 
The repository webpage shows this:

```
def GLIDE_VERSION = "4.13.2"
// webpdecoder
implementation "com.github.zjupure:webpdecoder:2.1.${GLIDE_VERSION}"
// glide 4.10.0+
implementation "com.github.bumptech.glide:glide:${GLIDE_VERSION}"
annotationProcessor "com.github.bumptech.glide:compiler:${GLIDE_VERSION}"
```

Yet it also talks about v2.1 and yet doesn't show how to use it on gradle file. Can you please explain?

**Comment by zjupure** [comment]
@AndroidDeveloperLB add mavenCentral() in your build.gradle

**Comment by AndroidDeveloperLB** [comment]
@zjupure I already have it. I don't understand how to use the new one.
Only this works, and it's actually what's still shown that I should do:

```
def GLIDE_VERSION = "4.13.2"
// webpdecoder
implementation "com.github.zjupure:webpdecoder:2.1.${GLIDE_VERSION}"
// glide 4.10.0+
implementation "com.github.bumptech.glide:glide:${GLIDE_VERSION}"
annotationProcessor "com.github.bumptech.glide:compiler:${GLIDE_VERSION}"
```

Yet on the release page, it says there is a newer version, and I don't understand what to change there to use it:
https://github.com/zjupure/GlideWebpDecoder/releases
