### ISSUE TITLE
Why not consider adding a method to stop at what frame?

### ISSUE THREAD

**Issue by liuhuan0225** [zjupure/GlideWebpDecoder#98]

**Comment by zjupure** [comment]
Could you show some specific use cases? It behaviors align with Gif images.

**Comment by how8570-syno-dev** [comment]
Gif can stop with `BaseRequestOptions#dontAnimate()`, but this not.

**Comment by how8570** [comment]
Gif can stop with `BaseRequestOptions#dontAnimate()`, but this not.
