### ISSUE TITLE
加载Duration小于20毫秒的webp图片动得很慢

### ISSUE THREAD

**Issue by ttooyy** [zjupure/GlideWebpDecoder#99]
在 WebpFrame 中定义的 MIN_FRAME_DURATION_MS 明明是 11
![image](https://user-images.githubusercontent.com/12596839/191301056-2054a53e-c29a-46cc-9419-1590c799be0e.png)
但是在WebpImage 中显示的是20 并且通过实际打印也是20
![image](https://user-images.githubusercontent.com/12596839/191301458-79f74594-e1ce-49cf-97dd-b8659f5bb272.png)

小于20毫秒的直接被赋值100 变得很慢，能否去掉 fixFrameDurations 这个方法啊

**Comment by zjupure** [comment]
Fixed in 10cd67186339949de3099e538b5e53996ebe9c9b. Please upgrade the library to 2.1 version, you could find in [mavenCentral](https://search.maven.org/artifact/com.github.zjupure/webpdecoder/2.1.4.13.2/aar).

**Comment by ttooyy** [comment]
就是最新版本2.1的

**Comment by ttooyy** [comment]
本来就是2.1
![image](https://user-images.githubusercontent.com/12596839/193167817-394f6a76-50ed-4bb6-a4e2-61b345718dda.png)
glide版本4.12.0

**Comment by zjupure** [comment]
编译缓存jar包有bug，重新发布了2.2版本
